### ISSUE TITLE
eMail output contains "\ Kein Zeilenumbruch am Dateiende." after most entries

### ISSUE THREAD

**Issue by ecm75** [idb-project/the-idb#485]
The automated Mail for new or changed entries contains an extra Line for most entries:
```
### Id ###

+1
\ Kein Zeilenumbruch am Dateiende.


### Inventory number ###



### Name ###

+WS-C2960G-24TC-L
\ Kein Zeilenumbruch am Dateiende.


### Serial ###

+FOC1501W3QN
\ Kein Zeilenumbruch am Dateiende.


### Part number ###



### Purchase date ###



### Warranty end ###



### Seller ###

+Cisco
\ Kein Zeilenumbruch am Dateiende.
```

Is this a setting issue or a bug? We are using the latest version from git develop branch (a8dc7f5).

**Comment by dra** [comment]
The IDB is using the diffy gem (https://github.com/samg/diffy) in order to create the diffs. There is an open issue regarding this behaviour:
https://github.com/samg/diffy/issues/88

We are not seeing this on our instances, I suppose it could be caused by default locale on the server (geman on your side?). Will try to reproduce and work around it.

**Comment by dra** [comment]
Found it, we had the similar problem but in english and already had to work around it. Adapted it to detect german wording as well, might you check with the latest commit?

**Comment by ecm75** [comment]
Yes the last commit fixed the problem for me.

This issue can be closed from my side.

THX!
